In [10]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import pandas as pd
import numpy as np
from classic_patterns import classic_ml_data
from labeling import label_tsla_data

## Juntando os dados
Pegando os dados

In [11]:
# Convertendo para numpy arrays, caso ainda não estejam
ml_tsla_data = np.array(classic_ml_data)  
label_tsla_data = np.array(label_tsla_data).ravel()

# Divide os dados em conjuntos de treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(ml_tsla_data, label_tsla_data, test_size=0.2, random_state=42)

## Fazendo a Rede Neural

In [22]:
def mlp(X_train, y_train, X_test, y_test, hidden_layers=(100, 100, 100), 
              activation='logistic', solver='adam', max_iter=500, random_state=42):
    """
    Treina um modelo de rede neural MLP e retorna as previsões e o relatório de classificação.

    Parâmetros:
    - X_train: Features do conjunto de treinamento.
    - y_train: Rótulos do conjunto de treinamento.
    - X_test: Features do conjunto de teste.
    - y_test: Rótulos do conjunto de teste.
    - hidden_layers: Tupla com o tamanho das camadas ocultas.
    - activation: Função de ativação a ser usada.
    - solver: Algoritmo de otimização a ser usado.
    - max_iter: Número máximo de iterações.
    - random_state: Semente para a geração de números aleatórios.

    Retorna:
    - y_pred_mlp: Previsões das classes no conjunto de teste.
    - report: Relatório de classificação.
    """
    
    # Define a rede neural com múltiplas camadas
    mlp = MLPClassifier(hidden_layer_sizes=hidden_layers, activation=activation,
                        solver=solver, max_iter=max_iter, random_state=random_state)

    # Treina a rede neural
    mlp.fit(X_train, y_train)

    # Faz previsões de probabilidade com o modelo MLP
    y_pred_probs_mlp = mlp.predict_proba(X_test)

    # Faz previsões de classe
    y_pred_mlp = mlp.predict(X_test)

    # Exibe o relatório de classificação para o MLP
    report = classification_report(y_test, y_pred_mlp)
    print(report)

    return y_pred_mlp, report

# Exemplo de uso
y_pred_mlp, report = mlp(X_train, y_train, X_test, y_test)

              precision    recall  f1-score   support

        -1.0       0.00      0.00      0.00         9
         0.0       0.00      0.00      0.00       357
         1.0       0.49      1.00      0.65       347

    accuracy                           0.49       713
   macro avg       0.16      0.33      0.22       713
weighted avg       0.24      0.49      0.32       713



c:\Users\Léo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Léo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Léo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier

## Fazendo o Modelo Random Forest

In [23]:
def random_forest(X_train, y_train, X_test, y_test, n_estimators=100, 
                        max_depth=10, random_state=42):
    """
    Treina um modelo de Random Forest e retorna as previsões e o relatório de classificação.

    Parâmetros:
    - X_train: Features do conjunto de treinamento.
    - y_train: Rótulos do conjunto de treinamento.
    - X_test: Features do conjunto de teste.
    - y_test: Rótulos do conjunto de teste.
    - n_estimators: Número de árvores na floresta.
    - max_depth: Profundidade máxima das árvores.
    - random_state: Semente para a geração de números aleatórios.

    Retorna:
    - y_pred_rf: Previsões das classes no conjunto de teste.
    - report: Relatório de classificação.
    """
    
    # Define o modelo Random Forest
    rf = RandomForestClassifier(n_estimators=n_estimators, max_depth=max_depth, 
                                 random_state=random_state)

    # Treina o modelo Random Forest
    rf.fit(X_train, y_train)

    # Faz previsões de probabilidade
    y_pred_probs = rf.predict_proba(X_test)

    # Faz previsões de classe
    y_pred_rf = rf.predict(X_test)

    # Exibe o relatório de classificação para o Random Forest
    report = classification_report(y_test, y_pred_rf)
    print(report)

    return y_pred_rf, report

# Exemplo de uso
y_pred_rf, report = random_forest(X_train, y_train, X_test, y_test)

              precision    recall  f1-score   support

        -1.0       0.00      0.00      0.00         9
         0.0       0.47      0.10      0.17       357
         1.0       0.48      0.88      0.63       347

    accuracy                           0.48       713
   macro avg       0.32      0.33      0.27       713
weighted avg       0.47      0.48      0.39       713



c:\Users\Léo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Léo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Léo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier

## Fazendo o Modelo Gradient Boosting

In [24]:
def gradient_boosting(X_train, y_train, X_test, y_test, random_state=42):
    """
    Treina um modelo de Gradient Boosting e retorna as previsões e o relatório de classificação.

    Parâmetros:
    - X_train: Features do conjunto de treinamento.
    - y_train: Rótulos do conjunto de treinamento.
    - X_test: Features do conjunto de teste.
    - y_test: Rótulos do conjunto de teste.
    - random_state: Semente para a geração de números aleatórios.

    Retorna:
    - y_pred_gb: Previsões das classes no conjunto de teste.
    - report: Relatório de classificação.
    """
    
    # Define o modelo Gradient Boosting
    gb_model = GradientBoostingClassifier(random_state=random_state)

    # Treina o modelo Gradient Boosting
    gb_model.fit(X_train, y_train)

    # Faz previsões de probabilidade
    y_pred_probs = gb_model.predict_proba(X_test)

    # Faz previsões de classe
    y_pred_gb = gb_model.predict(X_test)

    # Exibe o relatório de classificação para o Gradient Boosting
    report = classification_report(y_test, y_pred_gb)
    print(report)

    return y_pred_gb, report

# Exemplo de uso
y_pred_gb, report = gradient_boosting(X_train, y_train, X_test, y_test)

              precision    recall  f1-score   support

        -1.0       0.00      0.00      0.00         9
         0.0       0.45      0.07      0.12       357
         1.0       0.48      0.92      0.63       347

    accuracy                           0.48       713
   macro avg       0.31      0.33      0.25       713
weighted avg       0.46      0.48      0.37       713



c:\Users\Léo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Léo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Léo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier

In [57]:
print(y_pred_probs)

[[2.52374159e-03 1.96985076e-01 8.00491182e-01]
 [1.19982149e-02 4.84471646e-01 5.03530139e-01]
 [1.41937404e-03 4.40327581e-01 5.58253045e-01]
 ...
 [1.41937404e-03 4.40327581e-01 5.58253045e-01]
 [7.99688317e-04 4.84704645e-01 5.14495666e-01]
 [4.63652258e-03 4.78172482e-01 5.17190995e-01]]


In [56]:
# Faz previsões de probabilidade
y_pred_probs = rf.predict_proba(X_test)

# Identifica a classe com maior probabilidade
y_pred_indices = np.argmax(y_pred_probs, axis=1)

# Mapeia os índices para as classes de interesse
class_mapping = {0: 0, 1: 1, 2: -1}  # ajuste conforme necessário para sua classificação
y_pred = np.vectorize(class_mapping.get)(y_pred_indices)

# Avalia o modelo
print(classification_report(y_test, y_pred, target_names=["Desfazer Posição", "Compra", "Short"]))

                  precision    recall  f1-score   support

Desfazer Posição       0.01      0.78      0.02         9
          Compra       0.00      0.00      0.00       357
           Short       0.51      0.12      0.19       347

        accuracy                           0.07       713
       macro avg       0.17      0.30      0.07       713
    weighted avg       0.25      0.07      0.09       713



c:\Users\Léo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Léo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Léo\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier