In [25]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import pandas as pd
import numpy as np
from classic_patterns import ml_tsla_data
from labeling import label_tsla_data

## Juntando os dados
Pegando os dados

In [26]:
ml_tsla_data = np.array(ml_tsla_data)  
label_tsla_data = np.array(label_tsla_data).ravel()  

# Divide os dados em conjuntos de treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(ml_tsla_data, label_tsla_data, test_size=0.2, random_state=42)

## Fazendo a rede neural

In [27]:
# Define the neural network with multiple layers
# Adjust the hidden_layer_sizes parameter for more layers and units
mlp = MLPClassifier(hidden_layer_sizes=(100, 100, 100), activation='logistic', solver='adam', max_iter=500, random_state=42)

# Train the neural network
mlp.fit(X_train, y_train)

# Make predictions
y_pred_probs = mlp.predict_proba(X_test)


In [28]:
print(y_pred_probs.shape)
print(y_pred_probs)
# print(classification_report(y_test, y_pred_probs, target_names=["Desfazer Posição", "Compra", "Short"]))



(713, 3)
[[0.00664148 0.47996191 0.51339661]
 [0.00685358 0.48211    0.51103642]
 [0.00686925 0.4822323  0.51089845]
 ...
 [0.00686925 0.4822323  0.51089845]
 [0.00668008 0.48050195 0.51281797]
 [0.00669415 0.48061367 0.51269218]]


In [29]:
# Previsão das probabilidades
y_pred_probs = mlp.predict_proba(X_test)

# Mapeia as classes para 0, 1 e -1
# Considerando que a classe 0 corresponde a 'Desfazer Posição', 1 a 'Compra' e 2 a 'Short'
# Vamos usar np.argmax para encontrar a classe com maior probabilidade
y_pred_indices = np.argmax(y_pred_probs, axis=1)

# Mapeando os índices para -1, 0 e 1
# Supondo que:
# Classe 0 -> 0 (Desfazer Posição)
# Classe 1 -> 1 (Compra)
# Classe 2 -> -1 (Short)
class_mapping = {0: 0, 1: 1, 2: -1}
y_pred = np.vectorize(class_mapping.get)(y_pred_indices)

# Avalia o modelo
print(classification_report(y_test, y_pred, target_names=["Desfazer Posição", "Compra", "Short"]))

                  precision    recall  f1-score   support

Desfazer Posição       0.01      1.00      0.02         9
          Compra       0.00      0.00      0.00       357
           Short       0.00      0.00      0.00       347

        accuracy                           0.01       713
       macro avg       0.00      0.33      0.01       713
    weighted avg       0.00      0.01      0.00       713



C:\Users\kauan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\kauan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\kauan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\metrics\_classificati